# AWS credentials
# ideally leave blank, configure using `aws configure` instead, should then be defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# Database credentials
environment_variables:
    db_host:
    db_name:
    db_user:
    db_pwd:

# Lambda function defintion:
region:
function_name:
role:
description:

# Config details:
handler: service.handler
runtime: python2.7
dist_directory: dist
timeout: 30
memory_size: 512

# build options
build:
  source_directories: lib
